package example.suresh.domain.type;

public enum IncomeType {

	WAGES_AND_SALARIES,
	INTEREST_RECEIVED,
	DIVIDENDS,
	BUSINESS_INCOME,
	CAPITAL_GAINS_AND_LOSSES,
	PENSIONS_AND_ANNUITIES,
	PENSIONS,
	ROLLOVERS_FROM_RETIREMENT_PLANS,
	RENTAL_INCOME_AND_EXPENSES,
	FARMING_AND_FISHING_INCOME,
	EARNINGS_FOR_CLERGY,
	UNEMPLOYMENT_COMPENSATION,
	GAMBLING_INCOME_AND_LOSSES,
	BARTERING_INCOME,
	SCHOLARSHIPS,
	FELLOWSHIP_GRANTS,
	SOCIAL_SECURITY_AND_EQUIVALENT_RAILROAD_RETIREMENT_BENEFITS,
	FOUR_O_ONE_K_PLANS,
	STOCK_OPTIONS,
	TRADERS_IN_SECURITIES;

}
