package example.suresh.domain.type;

public enum MedicalConditionType {

		BLIND,
		DISABLED,
		AGED,
		MUSCULOSKELETAL_SYSTEM,
		SPECIAL_SENSES_AND_SPEECH,
		RESPIRATORY_DISORDERS,
		CARDIOVASCULAR_SYSTEM,
		DIGESTIVE_SYSTEM,
		GENITOURINARY_DISORDERS,
		HEMATOLOGICAL_DISORDERS,
		SKIN_DISORDERS,
		ENDOCRINE_DISORDERS,
		CONGENITAL_DISORDERS_THAT_AFFECT_MULTIPLE_BODY_SYSTEMS,
		NEUROLOGICAL_DISORDERS,
		MENTAL_DISORDERS,
		IMMUNE_SYSTEM_DISORDERS,
		OTHER;

}
